import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: "100%",
    maxWidth: "960px",
    margin: "0 auto",
    padding: "0 clamp(12px, 4vw, 24px)",
    boxSizing: "border-box",
  },
  statsOverlay: {
    position: "absolute",
    top: "clamp(8px, 2vw, 12px)",
    right: "clamp(8px, 2vw, 12px)",
    display: "flex",
    alignItems: "center",
    zIndex: 20,
  },
  statusBadge: {
    width: "clamp(10px, 2.5vw, 12px)",
    height: "clamp(10px, 2.5vw, 12px)",
    borderRadius: "9999px",
    display: "inline-block",
    border: "2px solid rgba(255, 255, 255, 0.9)",
    boxShadow: "0 0 0 1px rgba(0, 0, 0, 0.35)",
  },
  cameraContainer: {
    position: "relative",
    width: "100%",
    aspectRatio: "16 / 9",
    maxHeight: "calc(100dvh - 24px)",
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "#000",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.5)",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    transform: "scaleX(-1)",
  },
  canvas: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    transform: "scaleX(-1)",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
    zIndex: 10,
  },
  loadingText: {
    fontSize: "clamp(0.95rem, 3vw, 1.2rem)",
    color: "#00FF88",
    textAlign: "center",
    padding: "0 16px",
  },
  errorOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
    zIndex: 10,
  },
  errorText: {
    fontSize: "clamp(0.95rem, 3vw, 1.2rem)",
    color: "#FF3366",
    textAlign: "center",
    padding: "0 20px",
  },
};
